// Mock data matching API_CONTRACT.md shapes exactly
// Used until backend endpoints are live (Day 6 swap)

export const mockCaregiver = {
  id: 1,
  name: 'Parthiv',
  contact: 'parthiv@email.com',
  token: 'mock-jwt-token-caregiver',
};

export const mockPatients = [
  {
    id: 1,
    name: 'Meera Shah',
    age: 68,
    preferred_language: 'hi',
    photo_url: null,
    connection_status: 'connected',
    gender: 'female',
    phone: '+91 98765 43210',
    accessibility_prefs: { text_size: 'large', voice_volume: 80 },
  },
  {
    id: 2,
    name: 'Ramesh Patel',
    age: 74,
    preferred_language: 'gu',
    photo_url: null,
    connection_status: 'connected',
    gender: 'male',
    phone: '+91 98765 43211',
    accessibility_prefs: { text_size: 'xl', voice_volume: 90 },
  },
];

export const mockConnectionCode = {
  success: true,
  code: '482913',
  expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
};

export const mockMedications = [
  {
    id: 1,
    temp_id: 'm1',
    drug_name: 'Metformin',
    strength: '500mg',
    dose_per_intake: 1,
    form: 'tablet',
    frequency_per_day: 2,
    timing_slots: ['08:30', '20:30'],
    food_instruction: 'after_food',
    duration_days: 30,
    is_chronic: false,
    is_prn: false,
    special_instructions_en: 'Take twice a day, after food, for 30 days.',
    confidence: 'high',
    status: 'active',
    stock_remaining: 48,
    stock_status: 'ok',
    patient_id: 1,
  },
  {
    id: 2,
    temp_id: 'm2',
    drug_name: 'Amlodipine',
    strength: '5mg',
    dose_per_intake: 1,
    form: 'tablet',
    frequency_per_day: 1,
    timing_slots: ['08:30'],
    food_instruction: 'before_food',
    duration_days: 90,
    is_chronic: true,
    is_prn: false,
    special_instructions_en: 'Take once daily in the morning, before breakfast.',
    confidence: 'high',
    status: 'active',
    stock_remaining: 82,
    stock_status: 'ok',
    patient_id: 1,
  },
  {
    id: 3,
    temp_id: 'm3',
    drug_name: 'Aspirin',
    strength: '75mg',
    dose_per_intake: 1,
    form: 'tablet',
    frequency_per_day: 1,
    timing_slots: ['13:00'],
    food_instruction: 'after_food',
    duration_days: 90,
    is_chronic: true,
    is_prn: false,
    special_instructions_en: 'Take once daily after lunch.',
    confidence: 'high',
    status: 'active',
    stock_remaining: 6,
    stock_status: 'refill_soon',
    patient_id: 1,
  },
  {
    id: 4,
    temp_id: 'm4',
    drug_name: 'Pantoprazole',
    strength: '40mg',
    dose_per_intake: 1,
    form: 'tablet',
    frequency_per_day: 1,
    timing_slots: ['07:30'],
    food_instruction: 'before_food',
    duration_days: 14,
    is_chronic: false,
    is_prn: false,
    special_instructions_en: 'Take 30 minutes before breakfast on an empty stomach.',
    confidence: 'needs_review',
    status: 'active',
    stock_remaining: 10,
    stock_status: 'ok',
    patient_id: 1,
  },
  {
    id: 5,
    temp_id: 'm5',
    drug_name: 'Clopidogrel',
    strength: '75mg',
    dose_per_intake: 1,
    form: 'tablet',
    frequency_per_day: 1,
    timing_slots: ['20:30'],
    food_instruction: 'with_food',
    duration_days: 30,
    is_chronic: false,
    is_prn: false,
    special_instructions_en: 'Take once daily with dinner.',
    confidence: 'high',
    status: 'upcoming',
    stock_remaining: 30,
    stock_status: 'ok',
    patient_id: 1,
  },
];

export const mockInteractionFlags = [
  {
    id: 1,
    medication_ids: ['m3', 'm5'],
    drug_names: ['Aspirin 75mg', 'Clopidogrel 75mg'],
    severity: 'moderate',
    summary: 'May increase bleeding risk when taken together.',
    recommendation: 'Please confirm this combination with a doctor or pharmacist.',
    reviewed: false,
  },
];

export const mockPrescription = {
  success: true,
  prescription_id: 5,
  doctor_name: 'Dr. Sharma',
  hospital_name: 'City Hospital',
  ai_confidence_overall: 94,
  status: 'pending_review',
  uploaded_at: '2026-08-20T10:30:00',
  medications: mockMedications.slice(0, 4),
  interaction_flags: mockInteractionFlags,
  appointments: [
    {
      purpose: 'Follow-up review',
      doctor_name: 'Dr. Sharma',
      appointment_datetime: '2026-08-27T11:00:00',
    },
  ],
};

export const mockPrescriptions = [
  {
    id: 5,
    doctor_name: 'Dr. Sharma',
    hospital_name: 'City Hospital',
    ai_confidence_overall: 94,
    status: 'active',
    uploaded_at: '2026-08-20T10:30:00',
    medication_count: 4,
    patient_id: 1,
    patient_name: 'Meera Shah',
  },
  {
    id: 4,
    doctor_name: 'Dr. Patel',
    hospital_name: 'Gujarat Medical',
    ai_confidence_overall: 87,
    status: 'reviewed',
    uploaded_at: '2026-08-15T09:00:00',
    medication_count: 3,
    patient_id: 1,
    patient_name: 'Meera Shah',
  },
];

const now = new Date();
const today = now.toISOString().split('T')[0];

export const mockTodaySchedule = {
  current_reminder: {
    dose_log_id: 9,
    drug_name: 'Metformin',
    strength: '500mg',
    dose_per_intake: 1,
    form: 'tablet',
    food_instruction: 'after_food',
    image_url: null,
    audio_url: '/mock-audio.mp3',
    scheduled_time: `${today}T08:30:00`,
    status: 'pending',
  },
  upcoming_today: [
    {
      dose_log_id: 10,
      drug_name: 'Aspirin',
      strength: '75mg',
      dose_per_intake: 1,
      form: 'tablet',
      food_instruction: 'after_food',
      image_url: null,
      audio_url: '/mock-audio.mp3',
      scheduled_time: `${today}T13:00:00`,
      status: 'upcoming',
    },
    {
      dose_log_id: 11,
      drug_name: 'Metformin',
      strength: '500mg',
      dose_per_intake: 1,
      form: 'tablet',
      food_instruction: 'after_food',
      image_url: null,
      audio_url: '/mock-audio.mp3',
      scheduled_time: `${today}T20:30:00`,
      status: 'upcoming',
    },
    {
      dose_log_id: 12,
      drug_name: 'Clopidogrel',
      strength: '75mg',
      dose_per_intake: 1,
      form: 'tablet',
      food_instruction: 'with_food',
      image_url: null,
      audio_url: '/mock-audio.mp3',
      scheduled_time: `${today}T20:30:00`,
      status: 'upcoming',
    },
  ],
  completed_today: [
    {
      dose_log_id: 7,
      drug_name: 'Pantoprazole',
      strength: '40mg',
      dose_per_intake: 1,
      form: 'tablet',
      food_instruction: 'before_food',
      scheduled_time: `${today}T07:30:00`,
      status: 'taken',
      confirmed_at: `${today}T07:35:00`,
    },
    {
      dose_log_id: 8,
      drug_name: 'Amlodipine',
      strength: '5mg',
      dose_per_intake: 1,
      form: 'tablet',
      food_instruction: 'before_food',
      scheduled_time: `${today}T08:30:00`,
      status: 'taken',
      confirmed_at: `${today}T08:32:00`,
    },
  ],
  progress: { taken: 2, total: 6 },
};

export const mockDashboard = {
  adherence_today: { taken: 4, total: 5, percent: 80 },
  weekly_adherence: [
    { date: '2026-08-14', taken: 5, total: 5 },
    { date: '2026-08-15', taken: 4, total: 5 },
    { date: '2026-08-16', taken: 5, total: 5 },
    { date: '2026-08-17', taken: 3, total: 5 },
    { date: '2026-08-18', taken: 5, total: 5 },
    { date: '2026-08-19', taken: 4, total: 5 },
    { date: '2026-08-20', taken: 4, total: 5 },
  ],
  alerts: [
    {
      id: 1,
      type: 'safety',
      severity: 'red',
      message: 'Potential interaction between Aspirin and Clopidogrel — increased bleeding risk.',
      medicine: 'Aspirin 75mg + Clopidogrel 75mg',
      time: '2026-08-20T10:30:00',
      patient_id: 1,
      patient_name: 'Meera Shah',
      explanation: 'Both medications affect blood clotting. Taking them together may increase the risk of bleeding.',
      recommended_action: 'Confirm this combination with the prescribing doctor.',
      status: 'active',
    },
    {
      id: 2,
      type: 'missed_dose',
      severity: 'orange',
      message: 'Meera missed Metformin 500mg (evening dose) yesterday.',
      medicine: 'Metformin 500mg',
      time: '2026-08-19T21:30:00',
      patient_id: 1,
      patient_name: 'Meera Shah',
      explanation: 'The evening dose was not confirmed within the scheduled window.',
      recommended_action: 'Check with Meera about the missed dose and ensure she resumes the schedule.',
      status: 'active',
    },
    {
      id: 3,
      type: 'system',
      severity: 'yellow',
      message: 'Aspirin 75mg — only 6 tablets remaining. Refill soon.',
      medicine: 'Aspirin 75mg',
      time: '2026-08-20T06:00:00',
      patient_id: 1,
      patient_name: 'Meera Shah',
      explanation: 'At current dosing, the remaining stock will last approximately 6 days.',
      recommended_action: 'Arrange for a refill before stock runs out.',
      status: 'active',
    },
  ],
  upcoming_appointments: [
    {
      purpose: 'Follow-up review',
      doctor_name: 'Dr. Sharma',
      appointment_datetime: '2026-08-27T11:00:00',
    },
  ],
  medications: mockMedications.filter(m => m.status === 'active'),
  recent_activity: [
    { type: 'dose_confirmed', message: 'Meera confirmed Pantoprazole 40mg', time: `${today}T07:35:00` },
    { type: 'dose_confirmed', message: 'Meera confirmed Amlodipine 5mg', time: `${today}T08:32:00` },
    { type: 'alert_generated', message: 'Missed dose alert: Metformin 500mg (evening)', time: '2026-08-19T21:30:00' },
    { type: 'prescription_uploaded', message: 'Prescription from Dr. Sharma uploaded', time: '2026-08-20T10:30:00' },
    { type: 'plan_activated', message: 'Care plan activated for Meera Shah', time: '2026-08-20T10:45:00' },
  ],
};

export const mockHistory = {
  logs: [
    { medicine: 'Pantoprazole 40mg', scheduled_time: `${today}T07:30:00`, status: 'taken', confirmed_at: `${today}T07:35:00` },
    { medicine: 'Amlodipine 5mg', scheduled_time: `${today}T08:30:00`, status: 'taken', confirmed_at: `${today}T08:32:00` },
    { medicine: 'Metformin 500mg', scheduled_time: `${today}T08:30:00`, status: 'taken', confirmed_at: `${today}T08:40:00` },
    { medicine: 'Aspirin 75mg', scheduled_time: `${today}T13:00:00`, status: 'upcoming', confirmed_at: null },
    { medicine: 'Metformin 500mg', scheduled_time: `${today}T20:30:00`, status: 'upcoming', confirmed_at: null },
    { medicine: 'Metformin 500mg', scheduled_time: '2026-08-19T20:30:00', status: 'missed', confirmed_at: null },
    { medicine: 'Aspirin 75mg', scheduled_time: '2026-08-19T13:00:00', status: 'taken', confirmed_at: '2026-08-19T13:05:00' },
    { medicine: 'Metformin 500mg', scheduled_time: '2026-08-19T08:30:00', status: 'taken', confirmed_at: '2026-08-19T08:45:00' },
    { medicine: 'Amlodipine 5mg', scheduled_time: '2026-08-19T08:30:00', status: 'delayed', confirmed_at: '2026-08-19T09:15:00' },
    { medicine: 'Pantoprazole 40mg', scheduled_time: '2026-08-19T07:30:00', status: 'taken', confirmed_at: '2026-08-19T07:32:00' },
  ],
};

export const mockAuditLog = {
  entries: [
    { action: 'dose_confirmed', actor: 'patient', time: `${today}T08:40:00`, detail: 'Meera confirmed Metformin 500mg (morning dose)' },
    { action: 'dose_confirmed', actor: 'patient', time: `${today}T08:32:00`, detail: 'Meera confirmed Amlodipine 5mg' },
    { action: 'dose_confirmed', actor: 'patient', time: `${today}T07:35:00`, detail: 'Meera confirmed Pantoprazole 40mg' },
    { action: 'alert_generated', actor: 'system', time: '2026-08-19T21:30:00', detail: 'Missed dose alert generated for Metformin 500mg (evening)' },
    { action: 'dose_missed', actor: 'system', time: '2026-08-19T21:30:00', detail: 'Meera missed Metformin 500mg evening dose' },
    { action: 'prescription_uploaded', actor: 'caregiver', time: '2026-08-20T10:30:00', detail: 'Parthiv uploaded prescription from Dr. Sharma (City Hospital)' },
    { action: 'plan_activated', actor: 'caregiver', time: '2026-08-20T10:45:00', detail: 'Parthiv activated care plan — 4 medications for Meera Shah' },
    { action: 'alert_reviewed', actor: 'caregiver', time: '2026-08-20T11:00:00', detail: 'Parthiv reviewed interaction alert: Aspirin + Clopidogrel' },
    { action: 'patient_connected', actor: 'system', time: '2026-08-18T14:00:00', detail: 'Meera Shah connected via PIN code 482913' },
  ],
};

export const mockAlerts = mockDashboard.alerts;

// Auth mock responses
export const mockAuthResponses = {
  signup: { success: true, caregiver_id: 1, token: 'mock-jwt-token-caregiver' },
  login_caregiver: { success: true, role: 'caregiver', token: 'mock-jwt-token-caregiver', redirect: '/caregiver' },
  login_patient: { success: true, role: 'patient', token: 'mock-jwt-token-patient', redirect: '/patient' },
  forgot_password: { success: true, otp_sent: true },
  reset_password: { success: true },
};

// Error mock responses
export const mockErrors = {
  invalid_input: { success: false, error: { code: 'INVALID_INPUT', message: 'Invalid input provided.' } },
  unauthorized: { success: false, error: { code: 'UNAUTHORIZED', message: 'Invalid credentials.' } },
  code_expired: { success: false, error: { code: 'CODE_EXPIRED', message: 'This invitation code has expired. Ask your caregiver to generate a new code.' } },
  code_already_used: { success: false, error: { code: 'CODE_ALREADY_USED', message: 'This code has already been used.' } },
  not_found: { success: false, error: { code: 'NOT_FOUND', message: 'Resource not found.' } },
  ai_processing_failed: { success: false, error: { code: 'AI_PROCESSING_FAILED', message: 'AI processing failed. Please try again.' } },
};
